---
- name: Install epel
  yum: name=epel-release state=latest

- name: Install nginx
  yum: name=nginx state=present

- name: Allow port 4000 on firewall
  command: firewall-cmd --zone=public --add-service=http --permanent

- name: Reload firewall
  command: firewall-cmd --reload

- name: Copy nginx configuration for nodejs
  template: src=node.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx


